using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiplomacyLib
{
    public static class MapAdjacencyStrings
    {
        public static readonly Dictionary<string, List<string>> FullMap = new Dictionary<string, List<string>>()
        {
            { "nao", new List<string>() {"nwg", "cly", "lvp", "mao", "iri"} },
            { "iri", new List<string>() {"lvp", "wal", "eng", "mao", "nao"} },
            { "nwg", new List<string>() {"bar", "nwy", "nth", "edi", "cly"} },
            { "bar", new List<string>() {"stp", "nwy", "nwg"} },
            { "mao", new List<string>() {"nao", "iri", "eng", "bre", "gas", "spa", "por", "wes", "naf"} },
            { "lyo", new List<string>() {"spa", "mar", "pie", "tus", "tys", "wes"} },
            { "wes", new List<string>() {"mao", "spa", "lyo", "tys", "tun", "naf"} },
            { "tys", new List<string>() {"lyo", "tus", "rom", "nap", "ion", "tun", "wes"} },
            { "ion", new List<string>() {"tun", "tys", "nap", "apu", "adr", "alb", "gre", "aeg", "eas"} },
            { "adr", new List<string>() {"ven", "tri", "alb", "ion", "apu"} },
            { "aeg", new List<string>() {"gre", "bul", "con", "smy", "eas", "ion"} },
            { "bla", new List<string>() {"rum", "sev", "arm", "ank", "con", "bul"} },
            { "eas", new List<string>() {"ion", "aeg", "smy", "syr"} },
            { "nth", new List<string>() {"edi", "nwg", "nwy", "ska", "den", "hel", "hol", "bel", "eng", "lon", "yor"} },
            { "hel", new List<string>() {"nth", "den", "kie", "hol"} },
            { "ska", new List<string>() {"nth", "nwy", "swe", "den"} },
            { "bal", new List<string>() {"den", "swe", "bot", "lvn", "pru", "ber", "kie"} },
            { "bot", new List<string>() {"swe", "fin", "stp", "lvn", "bal"} },
            { "eng", new List<string>() {"iri", "wal", "lon", "nth", "bel", "pic", "bre", "mao"} },
            { "cly", new List<string>() {"nao", "nwg", "edi", "lvp"} },
            { "edi", new List<string>() {"cly", "nwg", "nth", "yor", "lvp"} },
            { "lvp", new List<string>() {"nao", "cly", "edi", "yor", "wal", "iri"} },
            { "yor", new List<string>() {"lvp", "edi", "nth", "lon", "wal"} },
            { "wal", new List<string>() {"iri", "lvp", "yor", "lon", "eng"} },
            { "lon", new List<string>() {"wal", "yor", "nth", "eng"} },
            { "nwy", new List<string>() {"nwg", "bar", "stp", "fin", "swe", "ska", "nth"} },
            { "swe", new List<string>() {"nwy", "fin", "bot", "bal", "den", "ska"} },
            { "fin", new List<string>() {"swe", "nwy", "stp", "bot"} },
            { "stp", new List<string>() {"nwy", "bar", "mos", "lvn", "bot", "fin"} },
            { "den", new List<string>() {"nth", "ska", "swe", "bal", "kie", "hel"} },
            { "lvn", new List<string>() {"bal", "bot", "stp", "mos", "war", "sil", "pru"} },
            { "bre", new List<string>() {"mao", "eng", "pic", "par", "gas"} },
            { "pic", new List<string>() {"bre", "eng", "bel", "bur", "par"} },
            { "bel", new List<string>() {"eng", "nth", "hol", "ruh", "bur", "pic"} },
            { "hol", new List<string>() {"nth", "hel", "kie", "ruh", "bel"} },
            { "kie", new List<string>() {"hel", "den", "bal", "ber", "mun", "ruh", "hol"} },
            { "ber", new List<string>() {"kie", "bal", "pru", "sil", "mun"} },
            { "pru", new List<string>() {"bal", "lvn", "war", "sil", "ber"} },
            { "sev", new List<string>() {"ukr", "mos", "arm", "bla", "rum"} },
            { "por", new List<string>() {"mao", "spa"} },
            { "spa", new List<string>() {"por", "mao", "gas", "mar", "lyo", "wes"} },
            { "gas", new List<string>() {"mao", "bre", "par", "bur", "mar", "spa"} },
            { "rum", new List<string>() {"bud", "gal", "ukr", "sev", "bla", "bul", "ser"} },
            { "arm", new List<string>() {"ank", "bla", "sev", "syr", "smy"} },
            { "naf", new List<string>() {"mao", "wes", "tun"} },
            { "mar", new List<string>() {"spa", "gas", "bur", "pie", "lyo"} },
            { "pie", new List<string>() {"mar", "tyr", "ven", "tus", "lyo"} },
            { "tri", new List<string>() {"ven", "tyr", "vie", "bud", "ser", "alb", "adr"} },
            { "ven", new List<string>() {"pie", "tyr", "tri", "adr", "apu", "rom", "tus"} },
            { "tus", new List<string>() {"pie", "ven", "rom", "tys", "lyo"} },
            { "rom", new List<string>() {"tus", "ven", "apu", "nap", "tys"} },
            { "nap", new List<string>() {"rom", "apu", "ion", "tys"} },
            { "apu", new List<string>() {"rom", "ven", "adr", "ion", "nap"} },
            { "tun", new List<string>() {"naf", "wes", "tys", "ion"} },
            { "alb", new List<string>() {"adr", "tri", "ser", "gre", "ion"} },
            { "gre", new List<string>() {"alb", "ser", "bul", "aeg", "ion"} },
            { "bul", new List<string>() {"ser", "rum", "bla", "con", "aeg", "gre"} },
            { "con", new List<string>() {"bul", "bla", "ank", "smy", "aeg"} },
            { "ank", new List<string>() {"con", "bla", "arm", "smy"} },
            { "smy", new List<string>() {"aeg", "con", "ank", "arm", "syr", "eas"} },
            { "syr", new List<string>() {"eas", "smy", "arm"} },
            { "bur", new List<string>() {"par", "pic", "bel", "ruh", "mun", "mar", "gas"} },
            { "par", new List<string>() {"bre", "pic", "bur", "gas"} },
            { "tyr", new List<string>() {"mun", "boh", "vie", "tri", "ven", "pie"} },
            { "ruh", new List<string>() {"bel", "hol", "kie", "mun", "bur"} },
            { "mun", new List<string>() {"bur", "ruh", "kie", "ber", "sil", "boh", "tyr"} },
            { "boh", new List<string>() {"mun", "sil", "gal", "vie", "tyr"} },
            { "sil", new List<string>() {"mun", "ber", "pru", "war", "gal", "boh"} },
            { "war", new List<string>() {"pru", "lvn", "mos", "ukr", "gal", "sil"} },
            { "mos", new List<string>() {"lvn", "stp", "sev", "ukr", "war"} },
            { "ukr", new List<string>() {"war", "mos", "sev", "rum", "gal"} },
            { "gal", new List<string>() {"boh", "sil", "war", "ukr", "rum", "bud", "vie"} },
            { "bud", new List<string>() {"vie", "gal", "rum", "ser", "tri"} },
            { "ser", new List<string>() {"tri", "bud", "rum", "bul", "gre", "alb"} },
            { "vie", new List<string>() {"boh", "gal", "bud", "tri", "tyr"} },
        };

        public static readonly Dictionary<string, List<string>> FleetMap = new Dictionary<string, List<string>>()
        {
            { "nao", new List<string>() {"nwg", "cly", "lvp", "mao", "iri"} },
            { "iri", new List<string>() {"lvp", "wal", "eng", "mao", "nao"} },
            { "nwg", new List<string>() {"bar", "nwy", "nth", "edi", "cly"} },
            { "bar", new List<string>() {"stp_nc", "nwy", "nwg"} },
            { "mao", new List<string>() {"nao", "iri", "eng", "bre", "gas", "spa_nc", "spa_sc", "por", "wes", "naf"} },
            { "lyo", new List<string>() {"spa_sc", "mar", "pie", "tus", "tys", "wes"} },
            { "wes", new List<string>() {"mao", "spa_sc", "lyo", "tys", "tun", "naf"} },
            { "tys", new List<string>() {"lyo", "tus", "rom", "nap", "ion", "tun", "wes"} },
            { "ion", new List<string>() {"tun", "tys", "nap", "apu", "adr", "alb", "gre", "aeg", "eas"} },
            { "adr", new List<string>() {"ven", "tri", "alb", "ion", "apu"} },
            { "aeg", new List<string>() {"gre", "bul_sc", "con", "smy", "eas", "ion"} },
            { "bla", new List<string>() {"rum", "sev", "arm", "ank", "con", "bul_ec"} },
            { "eas", new List<string>() {"ion", "aeg", "smy", "syr"} },
            { "nth", new List<string>() {"edi", "nwg", "nwy", "ska", "den", "hel", "hol", "bel", "eng", "lon", "yor"} },
            { "hel", new List<string>() {"nth", "den", "kie", "hol"} },
            { "ska", new List<string>() {"nth", "nwy", "swe", "den"} },
            { "bal", new List<string>() {"den", "swe", "bot", "lvn", "pru", "ber", "kie"} },
            { "bot", new List<string>() {"swe", "fin", "stp_sc", "lvn", "bal"} },
            { "eng", new List<string>() {"iri", "wal", "lon", "nth", "bel", "pic", "bre", "mao"} },
            { "cly", new List<string>() {"nao", "nwg", "edi", "lvp"} },
            { "edi", new List<string>() {"cly", "nwg", "nth", "yor"} },
            { "lvp", new List<string>() {"nao", "cly", "wal", "iri"} },
            { "yor", new List<string>() {"edi", "nth", "lon"} },
            { "wal", new List<string>() {"iri", "lvp", "lon", "eng"} },
            { "lon", new List<string>() {"wal", "yor", "nth", "eng"} },
            { "nwy", new List<string>() {"nwg", "bar", "stp_nc", "swe", "ska", "nth"} },
            { "swe", new List<string>() {"nwy", "fin", "bot", "bal", "den", "ska"} },
            { "fin", new List<string>() {"swe", "stp_sc", "bot"} },
            { "stp_nc", new List<string>() {"nwy", "bar"} },
            { "stp_sc", new List<string>() {"lvn", "bot", "fin"} },
            { "den", new List<string>() {"nth", "ska", "swe", "bal", "kie", "hel"} },
            { "lvn", new List<string>() {"bal", "bot", "stp_sc", "pru"} },
            { "bre", new List<string>() {"mao", "eng", "pic", "gas"} },
            { "pic", new List<string>() {"bre", "eng", "bel"} },
            { "bel", new List<string>() {"eng", "nth", "hol", "pic"} },
            { "hol", new List<string>() {"nth", "hel", "kie", "bel"} },
            { "kie", new List<string>() {"hel", "den", "bal", "ber", "hol"} },
            { "ber", new List<string>() {"kie", "bal", "pru"} },
            { "pru", new List<string>() {"bal", "lvn", "ber"} },
            { "sev", new List<string>() {"arm", "bla", "rum"} },
            { "por", new List<string>() {"mao", "spa_nc", "spa_sc"} },
            { "spa_nc", new List<string>() {"por", "mao", "gas"} },
            { "spa_sc", new List<string>() {"por", "mao", "mar", "lyo", "wes"} },
            { "gas", new List<string>() {"mao", "bre", "spa_nc"} },
            { "rum", new List<string>() {"sev", "bla", "bul_ec"} },
            { "arm", new List<string>() {"ank", "bla", "sev"} },
            { "naf", new List<string>() {"mao", "wes", "tun"} },
            { "mar", new List<string>() {"spa_sc", "pie", "lyo"} },
            { "pie", new List<string>() {"mar", "tus", "lyo"} },
            { "tri", new List<string>() {"ven", "alb", "adr"} },
            { "ven", new List<string>() {"tri", "adr", "apu"} },
            { "tus", new List<string>() {"pie", "rom", "tys", "lyo"} },
            { "rom", new List<string>() {"tus", "nap", "tys"} },
            { "nap", new List<string>() {"rom", "apu", "ion", "tys"} },
            { "apu", new List<string>() {"ven", "adr", "ion", "nap"} },
            { "tun", new List<string>() {"naf", "wes", "tys", "ion"} },
            { "alb", new List<string>() {"adr", "tri", "gre", "ion"} },
            { "gre", new List<string>() {"alb", "bul_sc", "aeg", "ion"} },
            { "bul_ec", new List<string>() {"rum", "bla", "con"} },
            { "bul_sc", new List<string>() {"con", "aeg", "gre"} },
            { "con", new List<string>() {"bul_sc", "bul_ec", "bla", "ank", "smy", "aeg"} },
            { "ank", new List<string>() {"con", "bla", "arm"} },
            { "smy", new List<string>() {"aeg", "con", "syr", "eas"} },
            { "syr", new List<string>() {"eas", "smy"} },
        };

        public static readonly Dictionary<string, List<string>> ArmyMap = new Dictionary<string, List<string>>()
        {
            { "cly", new List<string>() {"edi", "lvp"} },
            { "edi", new List<string>() {"cly", "yor", "lvp"} },
            { "lvp", new List<string>() {"cly", "edi", "yor", "wal"} },
            { "yor", new List<string>() {"lvp", "edi", "lon", "wal"} },
            { "wal", new List<string>() {"lvp", "yor", "lon"} },
            { "lon", new List<string>() {"wal", "yor"} },
            { "nwy", new List<string>() {"stp", "fin", "swe"} },
            { "swe", new List<string>() {"nwy", "fin", "den"} },
            { "fin", new List<string>() {"swe", "nwy", "stp"} },
            { "stp", new List<string>() {"nwy", "mos", "lvn", "fin"} },
            { "den", new List<string>() {"swe", "kie"} },
            { "lvn", new List<string>() {"stp", "mos", "war", "sil", "pru"} },
            { "bre", new List<string>() {"pic", "par", "gas"} },
            { "pic", new List<string>() {"bre", "bel", "bur", "par"} },
            { "bel", new List<string>() {"hol", "ruh", "bur", "pic"} },
            { "hol", new List<string>() {"kie", "ruh", "bel"} },
            { "kie", new List<string>() {"den", "ber", "mun", "ruh", "hol"} },
            { "ber", new List<string>() {"kie", "pru", "sil", "mun"} },
            { "pru", new List<string>() {"lvn", "war", "sil", "ber"} },
            { "sev", new List<string>() {"ukr", "mos", "arm", "rum"} },
            { "por", new List<string>() {"spa"} },
            { "spa", new List<string>() {"por", "gas", "mar"} },
            { "gas", new List<string>() {"bre", "par", "bur", "mar", "spa"} },
            { "rum", new List<string>() {"bud", "gal", "ukr", "sev", "bul", "ser"} },
            { "arm", new List<string>() {"ank", "sev", "syr", "smy"} },
            { "naf", new List<string>() {"tun"} },
            { "mar", new List<string>() {"spa", "gas", "bur", "pie"} },
            { "pie", new List<string>() {"mar", "tyr", "ven", "tus"} },
            { "tri", new List<string>() {"ven", "tyr", "vie", "bud", "ser", "alb"} },
            { "ven", new List<string>() {"pie", "tyr", "tri", "apu", "rom", "tus"} },
            { "tus", new List<string>() {"pie", "ven", "rom"} },
            { "rom", new List<string>() {"tus", "ven", "apu", "nap"} },
            { "nap", new List<string>() {"rom", "apu"} },
            { "apu", new List<string>() {"rom", "ven", "nap"} },
            { "tun", new List<string>() {"naf"} },
            { "alb", new List<string>() {"tri", "ser", "gre"} },
            { "gre", new List<string>() {"alb", "ser", "bul"} },
            { "bul", new List<string>() {"ser", "rum", "con", "gre"} },
            { "con", new List<string>() {"bul", "ank", "smy"} },
            { "ank", new List<string>() {"con", "arm", "smy"} },
            { "smy", new List<string>() {"con", "ank", "arm", "syr"} },
            { "syr", new List<string>() {"smy", "arm"} },
            { "bur", new List<string>() {"par", "pic", "bel", "ruh", "mun", "mar", "gas"} },
            { "par", new List<string>() {"bre", "pic", "bur", "gas"} },
            { "tyr", new List<string>() {"mun", "boh", "vie", "tri", "ven", "pie"} },
            { "ruh", new List<string>() {"bel", "hol", "kie", "mun", "bur"} },
            { "mun", new List<string>() {"bur", "ruh", "kie", "ber", "sil", "boh", "tyr"} },
            { "boh", new List<string>() {"mun", "sil", "gal", "vie", "tyr"} },
            { "sil", new List<string>() {"mun", "ber", "pru", "war", "gal", "boh"} },
            { "war", new List<string>() {"pru", "lvn", "mos", "ukr", "gal", "sil"} },
            { "mos", new List<string>() {"lvn", "stp", "sev", "ukr", "war"} },
            { "ukr", new List<string>() {"war", "mos", "sev", "rum", "gal"} },
            { "gal", new List<string>() {"boh", "sil", "war", "ukr", "rum", "bud", "vie"} },
            { "bud", new List<string>() {"vie", "gal", "rum", "ser", "tri"} },
            { "ser", new List<string>() {"tri", "bud", "rum", "bul", "gre", "alb"} },
            { "vie", new List<string>() {"boh", "gal", "bud", "tri", "tyr"} },
        };

        public static Dictionary<string, List<string>> ConvoyMap = new Dictionary<string, List<string>>()
{
{ "nao", new List<string>() {"nwg", "cly_1", "lvp_1", "mao", "iri", } },
{ "iri", new List<string>() {"lvp_2", "wal_2", "eng", "mao", "nao", } },
{ "nwg", new List<string>() {"bar", "nwy_3", "nth", "edi_3", "cly_3", } },
{ "bar", new List<string>() {"stp_nc_4", "nwy_4", "nwg", } },
{ "mao", new List<string>() {"nao", "iri", "eng", "bre_5", "gas_5", "spa_nc_5", "spa_sc_5", "por_5", "wes", "naf_5", } },
{ "lyo", new List<string>() {"spa_sc_6", "mar_6", "pie_6", "tus_6", "tys", "wes", } },
{ "wes", new List<string>() {"mao", "spa_sc_7", "lyo", "tys", "tun_7", "naf_7", } },
{ "tys", new List<string>() {"lyo", "tus_8", "rom_8", "nap_8", "ion", "tun_8", "wes", } },
{ "ion", new List<string>() {"tun_9", "tys", "nap_9", "apu_9", "adr", "alb_9", "gre_9", "aeg", "eas", } },
{ "adr", new List<string>() {"ven_10", "tri_10", "alb_10", "ion", "apu_10", } },
{ "aeg", new List<string>() {"gre_11", "bul_sc_11", "con_11", "smy_11", "eas", "ion", } },
{ "bla", new List<string>() {"rum_12", "sev_12", "arm_12", "ank_12", "con_12", "bul_ec_12", } },
{ "eas", new List<string>() {"ion", "aeg", "smy_13", "syr_13", } },
{ "nth", new List<string>() {"edi_14", "nwg", "nwy_14", "ska", "den_14", "hel", "hol_14", "bel_14", "eng", "lon_14", "yor_14", } },
{ "hel", new List<string>() {"nth", "den_15", "kie_15", "hol_15", } },
{ "ska", new List<string>() {"nth", "nwy_16", "swe_16", "den_16", } },
{ "bal", new List<string>() {"den_17", "swe_17", "bot", "lvn_17", "pru_17", "ber_17", "kie_17", } },
{ "bot", new List<string>() {"swe_18", "fin_18", "stp_sc_18", "lvn_18", "bal", } },
{ "eng", new List<string>() {"iri", "wal_19", "lon_19", "nth", "bel_19", "pic_19", "bre_19", "mao", } },
};



    }
}
